language: r
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_book
pandoc_version: 1.19.2.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y fonts-font-awesome
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
env:
  global:
    secure: spUmDsIOgitcd+c02Xvqh8/2Z2P1YIOXxndFyhVt7D8Lt8FaqZqrFaIHMs7CrVupXxYadXBz9gS2riGCcWRgB3JQBx6KGXD/M7pu7HgLnKDX5j6n5aTFxc51NQlP0LQSFWIdw23RoOrPTOiAGW8jHzEaISokhqgw7GZadfMFxULrTuYkQZ1D/FbW6GMmv6CbkTi8XIxHb+tN6X51PEQSsnvIRiA7C1qtSXGHqjW0eoIou/gN/jdv7Y1XPRqWsAmNmQe/8z8DWvQFB9eJM45G2gHc0D1QcTgaJe90BH5qmxkpSWrmDl4DrIBH+DxUy8Hpk7bamNZ7SmpNf+Ek5gJ92QDs+M7br+VzZ3j3qYbqCvoEZekvSy4Xuzq2vl+7QHzai7t7fiwZ/5a9Gtpexo5jtMVFxbhVcry3/+Cpxn6S5vqqhEXvPfWcJBj/BuypC1VTVRPH+Rfs0ypC65BIxGqoUteq8w+m8swZ89qkOTpvXKMRAf6i7q6LxOIrhwSpQ3JpuvnCgVPcY/yG2E1+Rx6t15Cb5VFQe42hjYAM3YK+qQmP9o9gxfSUIG93NUgbGwcRFGuN7d7cAnBJCRl4H/4xCnoVY3VG09WCmMUxGZ6+vp86tRz/PjXdnoIX1nDEQR6lN64SlgtAv+PwlZKzM55GuCdGLc9ZnSla/qX7La7i6/4=
sudo: false
notifications:
  slack:
    secure: EV4fM9uyxKCCsgiNe+tgD87hYgjtVbs+6cdyKywu2y1P+V59KBhSJ9PWoZVJwIMkcEAdTD8BxLk9Na3KGlkowDdfGyEMsVmy/+aKi+jXRRhJW3V7hmj7CWhWXM6nXdqm8iaACaAbJt8yP5HWLBjNcW0JSsA1u3XcH6hsuomnhbyi3MlYz6/qIbPYYl11m4Ok5VnI/v3NjDsrPTcHC7fXP5+fu1rN+WfFplYSP7/p3veXykWdcsB5fM+hovUrBue80w1ozdnppzlNjxH0BbeMHYRKIYPosXn3QS/vBf7t85bBm0GdibRd3aR7H+jVfeNnAH6dE3P7KPmv1bARNLRCcQXNAI+WC+L273XJnzA0wMQNay0CZkAlpLza8HwANtFSUvI8a1qRoB5kQaJzW1UDTiunmwO3BI4qjWdKOqiK4njVMB9LNL4+AFVDwJM1N7UV1f2ZzucVuKSITCI4CzpOyeLS3cc10xFtEiAOSWr4vOXqqDWfM33W9q3ROJ1881mZQbRKgwh3n+KxSp7KvDun9PXEhAZby/CMX88q+BEYjLyvjD5VmbqpTSRfk21Q91Ox6PCcA3Ia9MFP6rjoaoqp2DODYuLHGYhSgk/VehHjgiTj40xK23BKcmqmciOxPrWOpaVDe96n0qPQxJDzu094ytfaWWyL8cne7PKnog3BfKc=
